# hostname (and path) to the root eg. http://spf13.com/
baseurl = "http://blog.sword865.com"
# Site title
title = "悟剑阁"
# Copyright
copyright = "Copyright (c) 2015. All rights reserved."
# Language
languageCode = "zh-CN"
# Metadata format: "yaml", "toml", "json"
metaDataFormat = "toml"
# Theme to use (located in /themes/THEMENAME/)
theme = "hyde-y"
# Pagination
paginate = 9
paginatePath = "page"
disablePathToLower = true
hasCJKLanguage = true
[permalinks]
    post = "/:year/:month/:day/:slug/"
[taxonomies]
    tag = "tags"
    category = "categories"
    topic = "topics"
[author]
    name = "罗刹剑客"
    email = "sword865@163.com"
#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # use duoshuoShortname
    gentieKey = "543cd58c6e7b44ad8fade1767e9fbef2"
    # You can use markdown here.
    brand = "悟剑阁"
    topline = "阁中悟剑，红尘练心"
    # footline = "coding with <i class='fa fa-heart'></i>"
    # Sidebar position
    # false, true, "left", "right"
    sidebar = "left"
    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "default"
    # Google Analytics.
    # googleAnalytics = "Your Google Analytics tracking code"
    cnzzID = "1260888787"
    # Sidebar social links.
    github = "sword865" # Your Github profile ID
    bitbucket = "" # Your Bitbucket profile ID
    linkedin = "" # Your LinkedIn profile ID (from public URL)
    googleplus = "" # Your Google+ profile ID
    facebook = "" # Your Facebook profile ID
    twitter = "" # Your Twitter profile ID
    youtube = ""  # Your Youtube channel ID
    flattr = ""  # populate with your flattr uid
    flickr = "" # Your Flickr profile ID
    vimeo = "" # Your Vimeo profile ID
    # Sidebar RSS link: will only show up if there is a RSS feed
    # associated with the current page
    rss = true
[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []
